name: CMake Build and Release

permissions:
  contents: write  # Required to create tags/releases

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            git \
            zip \
            libgl1-mesa-dev \
            libx11-dev \
            libxrandr-dev \
            libxi-dev \
            libxcursor-dev \
            libxinerama-dev

      - name: Configure CMake (Linux)
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..

      - name: Build (Linux)
        run: |
          cd build
          cmake --build . --config Release

      - name: Zip build artifacts (Linux)
        run: |
          # Zip the contents of build/ into linux-x86_64.zip at repo root
          zip -r linux-x86_64.zip build/*

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x86_64
          path: linux-x86_64.zip

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake (Windows)
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..

      - name: Build (Windows)
        run: |
          cd build
          cmake --build . --config Release

      - name: Zip build artifacts (Windows)
        run: |
          powershell Compress-Archive -Path build\* -DestinationPath windows-x86_64.zip

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-x86_64
          path: windows-x86_64.zip

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Download both artifacts to the root folder
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-x86_64
          path: .

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-x86_64
          path: .

      # Create tag automatically (starting at v1.0.0)
      - name: Create tag
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git fetch --tags
          latest_tag=$(git tag --sort=-creatordate | head -n1)

          if [ -z "$latest_tag" ]; then
            new_tag="v1.0.0"
          else
            tag_core=${latest_tag#v}
            IFS='.' read -r major minor patch <<< "$tag_core"
            minor=${minor:-0}
            patch=${patch:-0}
            patch=$((patch+1))
            new_tag="v$major.$minor.$patch"
          fi

          echo "New tag: $new_tag"
          git tag $new_tag
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git $new_tag
          echo "tag=$new_tag" >> $GITHUB_OUTPUT
          sleep 5  # wait for GitHub to register the tag

      # Create GitHub release and attach both zipped artifacts
      - name: Create GitHub Release with artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Release ${{ steps.tag.outputs.tag }}
          body: Automated release from GitHub Actions
          files: |
            linux-x86_64.zip
            windows-x86_64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}